// Generates the GitOps artifact (a Kubernetes Job manifest pinned to the chosen
// region) + the pull-request title/body for a routing decision. Pure functions.

import { regionByName } from './regions'

export type DeploySpec = {
  workload: { name: string; mw: number; hours: number; profile?: string }
  region: string
  run_now: boolean
  defer_until?: string | null
  projected: {
    energy_cost_usd: number
    co2_tonnes: number
    savings_vs_worst_usd: number
    savings_vs_worst_co2_tonnes: number
    baseline_region: string
  }
  rationale: string
}

export type GitOpsArtifact = { path: string; yaml: string; branch: string; title: string; body: string }

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'workload'
const num = (n: number) => `${Math.round(n * 100) / 100}`

export function buildArtifact(spec: DeploySpec, stampMs: number): GitOpsArtifact {
  const meta = regionByName(spec.region)
  const cloudRegion = meta?.cloudRegion ?? 'us-east-1'
  const carbon = meta?.carbonFallback ?? 0
  const name = slug(spec.workload.name || `${spec.workload.profile ?? 'compute'}-job`)
  const stamp = stampMs
  const branch = `gridmind/deploy-${name}-${stamp}`
  const path = `deployments/${name}-${stamp}.yaml`
  const schedule = spec.run_now ? 'run immediately' : `deferred until ${spec.defer_until ?? 'cleaner window'}`

  const yaml = `# Generated by the GridMind routing agent
# Workload "${spec.workload.name}" routed to ${spec.region} (${cloudRegion}) — ${schedule}.
# Projected: $${num(spec.projected.energy_cost_usd)} energy, ${num(spec.projected.co2_tonnes)} t CO2.
# Saves $${num(spec.projected.savings_vs_worst_usd)} and ${num(spec.projected.savings_vs_worst_co2_tonnes)} t vs ${spec.projected.baseline_region}.
apiVersion: batch/v1
kind: Job
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/managed-by: gridmind
  annotations:
    gridmind.io/region: "${spec.region}"
    gridmind.io/cloud-region: "${cloudRegion}"
    gridmind.io/profile: "${spec.workload.profile ?? 'balanced'}"
    gridmind.io/schedule: "${spec.run_now ? 'now' : (spec.defer_until ?? 'deferred')}"
    gridmind.io/projected-cost-usd: "${num(spec.projected.energy_cost_usd)}"
    gridmind.io/projected-co2-tonnes: "${num(spec.projected.co2_tonnes)}"
    gridmind.io/grid-carbon-gco2-kwh: "${carbon}"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: gridmind
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: ["${cloudRegion}"]
      containers:
        - name: workload
          image: ghcr.io/your-org/${name}:latest
          resources:
            requests:
              cpu: "${Math.max(1, Math.round(spec.workload.mw))}"   # ~1 vCPU per MW (placeholder)
`

  const title = `Deploy ${spec.workload.name} → ${spec.region} (${cloudRegion})`
  const body = `## GridMind routing decision

**Route \`${spec.workload.name}\` → ${spec.region} (\`${cloudRegion}\`)** — ${spec.run_now ? 'run now' : `defer until ${spec.defer_until ?? 'cleaner window'}`}

| Metric | Value |
|---|---|
| Profile | ${spec.workload.profile ?? 'balanced'} |
| Size | ${spec.workload.mw} MW × ${spec.workload.hours} h |
| Projected energy cost | $${num(spec.projected.energy_cost_usd)} |
| Projected carbon | ${num(spec.projected.co2_tonnes)} t CO₂ |
| Savings vs ${spec.projected.baseline_region} | $${num(spec.projected.savings_vs_worst_usd)} · ${num(spec.projected.savings_vs_worst_co2_tonnes)} t CO₂ |

### Rationale
${spec.rationale}

---
*Opened automatically by the GridMind routing agent from live grid data. Review and merge to provision \`${path}\`.*`

  return { path, yaml, branch, title, body }
}
